### ISSUE TITLE
Invalid Entity ID specified.

### ISSUE THREAD

**Issue by magicclick-co** [anilkumarum/one-clipper#5]
Error: Invalid Entity ID specified.
Stack:
Request url:https://graph.microsoft.com/v1.0/me/onenote/pages/undefined/content
code:20112
ExtensionId: dnaodehopbbgbddbaojmfahnhlacjegi
Extension Name: oneClipper
Extension Version: 0.0.32
Browser Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/[130.0.0.0](http://130.0.0.0/) Safari/537.36

**Comment by anilkumarum** [comment]
I will fix this bug after 4 December. I am busy in Chrome built-in challenge project

**Comment by anilkumarum** [comment]
Bug fixed in v0.0.33.
Firefox extension also updated.
If none note is selected then only error caused.

Thanks
Have a nice day

**Comment by Teflondom25** [comment]
Problem is back?

Error: Invalid Entity ID specified.
Stack:
Request url:https://graph.microsoft.com/v1.0/me/onenote/pages/createPage/content
code:20112
ExtensionId: dnaodehopbbgbddbaojmfahnhlacjegi
Extension Name: oneClipper
Extension Version: 0.0.33
Browser Info: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36
